"""add_note_links_and_habits

Revision ID: 3b93a1943285
Revises: merge_automation_ical_001
Create Date: 2026-07-30 08:43:13.827727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b93a1943285'
down_revision: Union[str, None] = 'merge_automation_ical_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _has_index(table: str, index_name: str) -> bool:
    insp = sa.inspect(op.get_bind())
    return any(ix.get("name") == index_name for ix in insp.get_indexes(table))


def upgrade() -> None:
    # 幂等创建：表/索引已存在（老库通过 SQLModel schema 直接建过）则跳过，避免重复创建报错。
    if not _has_table('habit_records'):
        op.create_table('habit_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('habit_id', sa.Integer(), nullable=False),
        sa.Column('record_date', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if _has_table('habit_records'):
        with op.batch_alter_table('habit_records', schema=None) as batch_op:
            if not _has_index('habit_records', 'ix_habit_records_habit_id'):
                batch_op.create_index(batch_op.f('ix_habit_records_habit_id'), ['habit_id'], unique=False)
            if not _has_index('habit_records', 'ix_habit_records_record_date'):
                batch_op.create_index(batch_op.f('ix_habit_records_record_date'), ['record_date'], unique=False)

    if not _has_table('habits'):
        op.create_table('habits',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('persistence_days', sa.Integer(), nullable=False),
        sa.Column('group', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if _has_table('habits') and not _has_index('habits', 'ix_habits_uid'):
        with op.batch_alter_table('habits', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_habits_uid'), ['uid'], unique=False)

    if not _has_table('note_links'):
        op.create_table('note_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_note_id', sa.Integer(), nullable=False),
        sa.Column('target_note_id', sa.Integer(), nullable=False),
        sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('user_note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if _has_table('note_links'):
        with op.batch_alter_table('note_links', schema=None) as batch_op:
            if not _has_index('note_links', 'ix_note_links_source_note_id'):
                batch_op.create_index(batch_op.f('ix_note_links_source_note_id'), ['source_note_id'], unique=False)
            if not _has_index('note_links', 'ix_note_links_target_note_id'):
                batch_op.create_index(batch_op.f('ix_note_links_target_note_id'), ['target_note_id'], unique=False)

    if _has_table('journal_note_relations'):
        op.drop_table('journal_note_relations')
    # NOTE: ~40 drop_index commands removed — false positives from SQLModel ix_* vs legacy idx_* naming convention.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_note_relations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('journal_id', sa.INTEGER(), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_links_target_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_links_source_note_id'))

    op.drop_table('note_links')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_uid'))

    op.drop_table('habits')
    with op.batch_alter_table('habit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_records_record_date'))
        batch_op.drop_index(batch_op.f('ix_habit_records_habit_id'))

    op.drop_table('habit_records')
    # ### end Alembic commands ###
