"""add project_type to projects

Revision ID: cf0bcf76731f
Revises: add_user_avatar_001
Create Date: 2026-08-18 14:10:19.140422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf0bcf76731f'
down_revision: Union[str, None] = 'add_user_avatar_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activities_end_time'))
        batch_op.drop_index(batch_op.f('idx_activities_start_time'))

    with op.batch_alter_table('activity_event_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activity_event_relations_activity_id'))
        batch_op.drop_index(batch_op.f('idx_activity_event_relations_event_id'))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attachments_deleted_at'))
        batch_op.drop_index(batch_op.f('idx_attachments_file_hash'))

    with op.batch_alter_table('audio_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audio_recordings_deleted_at'))
        batch_op.drop_index(batch_op.f('idx_audio_recordings_start_time'))
        batch_op.drop_index(batch_op.f('idx_audio_recordings_status'))

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chats_session_id'))

    with op.batch_alter_table('collection_note_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_note_relations_collection_id'))
        batch_op.drop_index(batch_op.f('ix_collection_note_relations_journal_id'))

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_updated_at'))

    with op.batch_alter_table('journal_activity_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journal_activity_relations_activity_id'))
        batch_op.drop_index(batch_op.f('idx_journal_activity_relations_journal_id'))

    with op.batch_alter_table('journal_tag_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journal_tag_relations_journal_id'))
        batch_op.drop_index(batch_op.f('idx_journal_tag_relations_tag_id'))

    with op.batch_alter_table('journal_todo_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journal_todo_relations_journal_id'))
        batch_op.drop_index(batch_op.f('idx_journal_todo_relations_todo_id'))

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journals_date'))
        batch_op.drop_index(batch_op.f('idx_journals_deleted_at'))
        batch_op.drop_index(batch_op.f('idx_journals_uid'))
        batch_op.drop_index(batch_op.f('ix_journals_updated_at'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_messages_chat_id'))

    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ocr_results_screenshot_id'))
        batch_op.drop_index(batch_op.f('idx_ocr_results_text_hash'))

    with op.batch_alter_table('project_note_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_note_relations_journal_id'))
        batch_op.drop_index(batch_op.f('ix_project_note_relations_project_id'))

    with op.batch_alter_table('project_todo_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_todo_relations_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_todo_relations_todo_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='project'))

    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_screenshots_app_name'))
        batch_op.drop_index(batch_op.f('idx_screenshots_created_at'))
        batch_op.drop_index(batch_op.f('idx_screenshots_event_id'))

    with op.batch_alter_table('sync_op_log', schema=None) as batch_op:
        batch_op.alter_column('result_json',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tags_deleted_at'))
        batch_op.drop_index(batch_op.f('idx_tags_tag_name_unique'))

    with op.batch_alter_table('todo_attachment_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_todo_attachment_relations_attachment_id'))
        batch_op.drop_index(batch_op.f('idx_todo_attachment_relations_todo_id'))

    with op.batch_alter_table('todo_tag_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_todo_tag_relations_tag_id'))
        batch_op.drop_index(batch_op.f('idx_todo_tag_relations_todo_id'))

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_todos_deleted_at'))
        batch_op.drop_index(batch_op.f('idx_todos_order'))
        batch_op.drop_index(batch_op.f('idx_todos_parent_todo_id'))
        batch_op.drop_index(batch_op.f('idx_todos_priority'))
        batch_op.drop_index(batch_op.f('idx_todos_status'))
        batch_op.drop_index(batch_op.f('idx_todos_uid'))
        batch_op.drop_index(batch_op.f('ix_todos_updated_at'))

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transcriptions_audio_recording_id'))
        batch_op.drop_index(batch_op.f('idx_transcriptions_extraction_status'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('zero_think_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_zero_think_cards_date'))
        batch_op.drop_index(batch_op.f('idx_zero_think_cards_user_date'))
        batch_op.drop_index(batch_op.f('idx_zero_think_cards_user_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zero_think_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_zero_think_cards_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_zero_think_cards_user_date'), ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_zero_think_cards_date'), ['date'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transcriptions_extraction_status'), ['extraction_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_transcriptions_audio_recording_id'), ['audio_recording_id'], unique=False)

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_uid'), ['uid'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_parent_todo_id'), ['parent_todo_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('idx_todos_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('todo_tag_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_todo_tag_relations_todo_id'), ['todo_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_todo_tag_relations_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('todo_attachment_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_todo_attachment_relations_todo_id'), ['todo_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_todo_attachment_relations_attachment_id'), ['attachment_id'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tags_tag_name_unique'), ['tag_name'], unique=1)
        batch_op.create_index(batch_op.f('idx_tags_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('sync_op_log', schema=None) as batch_op:
        batch_op.alter_column('result_json',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_screenshots_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_screenshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_screenshots_app_name'), ['app_name'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('project_type')

    with op.batch_alter_table('project_todo_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_todo_relations_todo_id'), ['todo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_todo_relations_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project_note_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_note_relations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_note_relations_journal_id'), ['journal_id'], unique=False)

    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ocr_results_text_hash'), ['text_hash'], unique=False)
        batch_op.create_index(batch_op.f('idx_ocr_results_screenshot_id'), ['screenshot_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_messages_chat_id'), ['chat_id'], unique=False)

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_journals_uid'), ['uid'], unique=False)
        batch_op.create_index(batch_op.f('idx_journals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_journals_date'), ['date'], unique=False)

    with op.batch_alter_table('journal_todo_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_journal_todo_relations_todo_id'), ['todo_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_journal_todo_relations_journal_id'), ['journal_id'], unique=False)

    with op.batch_alter_table('journal_tag_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_journal_tag_relations_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_journal_tag_relations_journal_id'), ['journal_id'], unique=False)

    with op.batch_alter_table('journal_activity_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_journal_activity_relations_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_journal_activity_relations_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('collection_note_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_note_relations_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_note_relations_collection_id'), ['collection_id'], unique=False)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chats_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('audio_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audio_recordings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_audio_recordings_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_audio_recordings_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attachments_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('idx_attachments_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('activity_event_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_activity_event_relations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_event_relations_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_activities_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_activities_end_time'), ['end_time'], unique=False)

    # ### end Alembic commands ###
